language: java

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

env:
  global:
    - MAVEN_OPTS="-Djna.library.path=/usr/lib -DskipTests=false -DfailIfNoTests=false"

before_install:
  - sudo apt-get install libhdf5-serial-dev
  - sudo dpkg -i ${TRAVIS_BUILD_DIR}/travis/netCDF-*-Linux.deb
  - wget http://www.unidata.ucar.edu/staff/rmay/maven-repo.tar.gz
  - tar -C $HOME/.m2 -xf maven-repo.tar.gz

install:
  - mvn install -DskipTests=true

script:
  - cd cdm && mvn test ${MAVEN_OPTS}
  - cd ../udunits && mvn test ${MAVEN_OPTS}
  - cd ../ui && mvn test ${MAVEN_OPTS}
  - cd ../waterml && mvn test ${MAVEN_OPTS}
    #- cd ../dap4/d4tests && mvn test ${MAVEN_OPTS}

cache:
  directories:
    - $HOME/.m2
