language: java
sudo: false

env:
  global:
    - BUILD_IDV=false
    - GRADLE_OPTS="-Djna.library.path=${TRAVIS_BUILD_DIR}/travis/lib/ubuntu-12.04.5-amd64"

matrix:
  include:
    - jdk: oraclejdk7
    - jdk: oraclejdk8
    - jdk: openjdk7
#      env: BUILD_IDV=true

script:
  # If we need to do an IDV build, run the script
  - if [[ $BUILD_IDV == true ]]; then
      travis/build_idv.sh;
    fi

  - if [[ $BUILD_IDV == false ]]; then
      ./gradlew --info testAll;
    fi

cache:
  directories:
    - $HOME/.gradle
