language: java
sudo: false

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

script:
  # Need to add back d4tests, eventually cdm-test
  - ./gradlew --info test

cache:
  directories:
    - $HOME/.gradle
