jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

install: mvn install -DskipTests=true

script:
    - cd udunits && mvn test -DskipTests=false -DfailIfNoTests=false -DtestFailureIgnore=true
    - cd ../waterml && mvn test -DskipTests=false -DfailIfNoTests=false -DtestFailureIgnore=true

matrix:
  allow_failures:
    - jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2
