jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

install: mvn install -DskipTests=true

script:
    - cd cdm && mvn test -DskipTests=false -DfailIfNoTests=false
    - cd ../udunits && mvn test -DskipTests=false -DfailIfNoTests=false
    - cd ../waterml && mvn test -DskipTests=false -DfailIfNoTests=false

matrix:
  allow_failures:
    - jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2
