language: java
sudo: false

env:
  global:
    - BUILD_IDV=false

matrix:
  include:
    - jdk: oraclejdk7
    - jdk: oraclejdk8
    - jdk: openjdk7
#    - jdk: oraclejdk7
#      env: BUILD_IDV=true

script:
  # If we need to do an IDV build, run the script
  - if [[ $BUILD_IDV == true ]]; then travis/build_idv.sh; fi
  # Need to add back d4tests, eventually cdm-test
  - if [[ $BUILD_IDV == false ]]; then ./gradlew --info :cdm:test :grib:test :udunits:test :ui:test :waterml:test; fi

cache:
  directories:
    - $HOME/.gradle
